####  Covid-19 Data Source: https://covid19.who.int/info/

In [55]:
import pandas as pd

In [56]:
#read csv file from url 
url1 = 'https://covid19.who.int/WHO-COVID-19-global-data.csv'
df = pd.read_csv(url1)
df.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-03,AF,Afghanistan,EMRO,0,0,0,0
1,2020-01-04,AF,Afghanistan,EMRO,0,0,0,0
2,2020-01-05,AF,Afghanistan,EMRO,0,0,0,0
3,2020-01-06,AF,Afghanistan,EMRO,0,0,0,0
4,2020-01-07,AF,Afghanistan,EMRO,0,0,0,0

In [57]:
#To store csv file into local machine
df.to_csv("WHO_COVID-19_global_regular_data.csv")

In [58]:
df1 = pd.read_csv("https://covid19.who.int/WHO-COVID-19-global-table-data.csv",index_col=False)
df1.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
0,Global,NaN,206958371,2655.170946,4256103,54.603643,404099,4357179,55.900397,63233,0.811247,5993
1,United States of America,Americas,36385257,10992.440000,778272,235.130000,0,615747,186.020000,3889,1.170000,0
2,India,South-East Asia,32225513,2335.170000,255559,18.520000,32937,431642,31.280000,3333,0.240000,417
3,Brazil,Americas,20350142,9573.860000,198363,93.320000,31142,568788,267.590000,6036,2.840000,926
4,Russian Federation,Europe,6600836,4523.150000,153086,104.900000,21624,170499,116.830000,5618,3.850000,816

In [59]:
#extract total covid-19 global data
df2 = df1[df1['WHO Region'].isna()]
df2.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
0,Global,NaN,206958371,2655.170946,4256103,54.603643,404099,4357179,55.900397,63233,0.811247,5993

In [60]:
#To store file
df2.to_csv("WHO_COVID_19_global_total_data.csv")

In [61]:
#extract countrywise total covid-19  data
df3 = df1[~df1['WHO Region'].isna()]
df3.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
1,United States of America,Americas,36385257,10992.44,778272,235.13,0,615747,186.02,3889,1.17,0
2,India,South-East Asia,32225513,2335.17,255559,18.52,32937,431642,31.28,3333,0.24,417
3,Brazil,Americas,20350142,9573.86,198363,93.32,31142,568788,267.59,6036,2.84,926
4,Russian Federation,Europe,6600836,4523.15,153086,104.90,21624,170499,116.83,5618,3.85,816
5,France,Europe,6287203,9666.77,145960,224.42,18398,111400,171.28,324,0.50,10

In [62]:
#To store file
df3.to_csv("WHO_COVID_19_Country_total_data.csv")

In [63]:
#read vaccination global data
df4 = pd.read_csv('https://covid19.who.int/who-data/vaccination-data.csv')
df4.head()

,COUNTRY,ISO3,WHO_REGION,DATA_SOURCE,DATE_UPDATED,TOTAL_VACCINATIONS,PERSONS_VACCINATED_1PLUS_DOSE,TOTAL_VACCINATIONS_PER100,PERSONS_VACCINATED_1PLUS_DOSE_PER100,PERSONS_FULLY_VACCINATED,PERSONS_FULLY_VACCINATED_PER100,VACCINES_USED,FIRST_VACCINE_DATE,NUMBER_VACCINES_TYPES_USED
0,Afghanistan,AFG,EMRO,REPORTING,2021-08-11,1809517.0,770302.0,4.648,1.979,1039215.0,2.670,"Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2...",2021-02-22,4.0
1,Albania,ALB,EURO,REPORTING,2021-08-08,1253028.0,701435.0,43.500,24.374,551593.0,19.167,"AstraZeneca - Vaxzevria,Gamaleya - Sputnik V,P...",2021-01-13,5.0
2,Algeria,DZA,AFRO,REPORTING,2021-08-16,NaN,NaN,NaN,NaN,NaN,NaN,"Beijing CNBG - BBIBP-CorV,Gamaleya - Sputnik V...",2021-01-30,3.0
3,American Samoa,ASM,WPRO,REPORTING,2021-08-09,52769.0,29210.0,95.601,52.920,24104.0,43.669,"Janssen - Ad26.COV 2.5,Moderna - mRNA-1273,Pfi...",2020-12-21,3.0
4,Andorra,AND,EURO,REPORTING,2021-08-01,86320.0,50747.0,111.700,65.679,35573.0,46.040,"AstraZeneca - Vaxzevria,Moderna - mRNA-1273,Pf...",2021-01-20,3.0

In [64]:
#To store vaccination file
df4.to_csv("WHO_COVID_19_Country_vaccination_data.csv")